services:
  redis-ut:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  solr-ut:
    image: ontoportal/solr-ut:0.1.0
    ports:
      - 8983:8983
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8983/solr/term_search_core1/admin/ping?wt=json | grep -iq '\"status\":\"OK\"}'  || exit 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  agraph-ut:
    image: franzinc/agraph:v8.1.0
    platform: linux/amd64
    environment:
      - AGRAPH_SUPER_USER=test
      - AGRAPH_SUPER_PASSWORD=xyzzy
    shm_size: 1g
    ports:
      - 10000-10035:10000-10035
    volumes:
      - agdata:/agraph/data
      #      - ./agraph/etc:/agraph/etc
    command: >
        bash -c "/agraph/bin/agraph-control --config /agraph/etc/agraph.cfg start
        ; agtool repos create ontoportal_test --supersede
        ; agtool users add anonymous
        ; agtool users grant anonymous root:ontoportal_test:rw
        ; tail -f /agraph/data/agraph.log"
    healthcheck:
      test: ["CMD-SHELL", "agtool storage-report ontoportal_test || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    profiles:
      - ag

  4store-ut:
    image: bde2020/4store
    platform: linux/amd64
    ports:
      - 9000:9000
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"
    profiles:
      - fs
volumes:
  agdata:
