require "sparql/client"

require_relative "mixins/query_pattern"
require_relative "mixins/solution_lang_filter"
require_relative "query_builder"
require_relative "solutions_mapper"
require_relative "client"
require_relative "triples"
require_relative "loader"
require_relative "queries"
